targets:
  $default:
    builders:
      json_serializable:
        options:
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          include_if_null: true
      thiltal_typescript_generator|thiltal_typescript_reporter:
        options:
          first: import {UnitTypeName} from './unit/types.g';import {ImageName} from './unit/images.g';import {ItemName} from './unit/items.g';