targets:
  $default:
    builders:
      typescript_generator|typescript_reporter:
        enabled: true

builders:
  typescript_reporter:
    target: ":thiltal_typescript_generator"
    import: "package:thiltal_typescript_generator/builder.dart"
    builder_factories: ["typescriptReporter"]
    build_extensions: {".dart": [".generate_typescript.g.part"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]