name: thiltal_typescript_generator
description: Generate typescript envelope for potentially json serializable dart class
version: 0.0.1
author: Zdeněk Mlčoch <mlcoch.zdenek@gmail.com>

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  build: any
  source_gen: any
  thiltal_typescript_reporter:
    path: ../thiltal_typescript_reporter

  
dev_dependencies:
  build_test: any
  build_runner: any
  test: any
